# Generated by Django 4.0.7 on 2023-05-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
