# Generated by Django 4.1.7 on 2023-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_like_post_remove_like_user_delete_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
