# Generated by Django 4.0.7 on 2023-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
